<?if(!defined("CORE_PROLOG_INCLUDED") || CORE_PROLOG_INCLUDED!==true)die();?>
<?
function PrepareParts($rsParts){
	$arUnique = Array();
	while($arPart = $rsParts->GetNext()){
		$PSTAMP = $arPart['ART_ARTICLE_NR'].$arPart['SUP_BRAND'];
		if(in_array($PSTAMP,$arUnique)){continue;}
		$arUnique[] = $PSTAMP;
		$arPart = PreparePart($arPart);
		$arResult['ANRS'][] = $arPart['NUMBER'];
		$arResult['PARTS'][] = $arPart;
	}
	return $arResult;
}

function PreparePart($arPart){
	$arPart = FirstPic($arPart);
	$arPart = PartTexts($arPart);
	return $arPart;
}
function FirstPic($arPart){
	global $TCore;
	$FPREFIX = $TCore->arSettings['MAIN']['TECDOC_FILES_PREFIX'];
	//Images
	if($arPart['ART_ID']>0 AND $FPREFIX!=''){
		$rsImg = TDSQL::GetImages($arPart['ART_ID'],TECDOC_LNG_ID,1);
		if($arImg = $rsImg->GetNext()){
			$arPart['IMG'] = $arImg['PATH']; // [PATH] => images/2/804197.jpg
		}
	}
	return $arPart;
}
function PartTexts($arPart){
	$arPart['PART_NAME']=trim($arPart['PART_NAME']);
	if($arPart['PART_NAME']==''){$arPart['PART_NAME'] = trim($arPart['ART_COMPLETE_DES_TEXT']);}
	if($arPart['PART_NAME']==''){$arPart['PART_NAME']=trim($arPart['STR_DES_TEXT']);}
	unset($arPart['ART_COMPLETE_DES_TEXT']); unset($arPart['STR_DES_TEXT']);
	//if($arPart['ART_COMPLETE_DES_TEXT']==$arPart['STR_DES_TEXT']){$arPart['STR_DES_TEXT']='';}
	if($arPart['SUP_BRAND']!=''){$arPart['SUP_BRAND']=StrToUp($arPart['SUP_BRAND']); $arPart['SUP_BRAND_F']=BrandNameEncode($arPart['SUP_BRAND']);}
	if($arPart['ART_ARTICLE_NR']!=''){$ToNumber=$arPart['ART_ARTICLE_NR'];}elseif($arPart['ART_NUM']!=''){$ToNumber=$arPart['ART_NUM'];}
	$arPart['NUMBER'] = StrToUp(ArtToNumber($ToNumber,'FULL'));
	$arPart['NUMBER_SHORT'] = StrToUp(ArtToNumber($ToNumber,'SHORT'));
	return $arPart;
}

function BrandNameEncode($Bname){
	$Bname=str_replace("'",'_a_',$Bname);
	$Bname=str_replace(' & ','_and_',$Bname);
	$Bname=str_replace('&','and',$Bname);
	$Bname=str_replace(' + ','_plus_',$Bname);
	$Bname=str_replace('+','_cplus_',$Bname);
	$Bname=str_replace(' ','_',$Bname);
	$Bname=StrToLow($Bname);
	return $Bname;
}
function BrandNameDecode($Bname){
	$Bname = mysql_real_escape_string(substr($Bname,0,60));
	$Bname=str_replace('_a_',"'",$Bname);
	$Bname=str_replace('_and_',' & ',$Bname);
	$Bname=str_replace('and','&',$Bname);
	$Bname=str_replace('_plus_',' + ',$Bname);
	$Bname=str_replace('_cplus_','+',$Bname);
	$Bname=str_replace('_',' ',$Bname);
	$Bname=str_replace('/','',$Bname);
	$Bname=StrToUp($Bname);	
	return $Bname;
}

class TDSQL{
	//Manufacturers
	static function GetManufs(){
		$SQL='SELECT MFA_BRAND, MFA_MFC_CODE, MFA_ID FROM MANUFACTURERS ORDER BY MFA_BRAND';
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Brands by id
	static function GetManufByID($BName){
		$BName = str_replace('_',' ',$BName);
		$SQL='SELECT MFA_BRAND, MFA_MFC_CODE, MFA_ID FROM MANUFACTURERS WHERE MFA_BRAND = "'.$BName.'"';
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Models auto by id brands
	static function GetModels($MFA_ID,$LNG_ID,$arFilter=Array(),$Not=false,$YearFrom){
		if($YearFrom<=0){$YearFrom=MODELS_START_YEAR_LIMIT;}
		if(count($arFilter)>0){
			if($Not==true){$NOT_FILTER=' NOT ';}
			$IN_FILTER=' AND MOD_ID '.$NOT_FILTER.' IN ('.implode(',',$arFilter).')';
		}
		$SQL='SELECT MOD_ID, TEX_TEXT AS MOD_CDS_TEXT, MOD_PCON_START, MOD_PCON_END 
			FROM MODELS 
				INNER JOIN COUNTRY_DESIGNATIONS ON CDS_ID = MOD_CDS_ID
				INNER JOIN DES_TEXTS ON TEX_ID = CDS_TEX_ID
			WHERE
				MOD_MFA_ID = '.$MFA_ID.' AND CDS_LNG_ID = '.$LNG_ID.' AND MOD_PCON_START > '.$YearFrom.'00 '.$IN_FILTER.' 
			GROUP BY MOD_ID ORDER BY MOD_CDS_TEXT';
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Models auto by id
	static function GetModelByID($MFA_ID,$MOD_ID,$LNG_ID){
		$SQL='SELECT MOD_ID, TEX_TEXT AS MOD_CDS_TEXT, MOD_PCON_START, MOD_PCON_END 
			FROM MODELS 
					INNER JOIN COUNTRY_DESIGNATIONS ON CDS_ID = MOD_CDS_ID
					INNER JOIN DES_TEXTS ON TEX_ID = CDS_TEX_ID
			WHERE MOD_MFA_ID = '.$MFA_ID.' AND MOD_ID = '.$MOD_ID.' AND CDS_LNG_ID = '.$LNG_ID;
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Types auto by id brands
	static function GetTypes($MOD_ID,$LNG_ID){
        $SQL='SELECT
					TYP_ID, DES_TEXTS.TEX_TEXT AS TYP_CDS_TEXT, TYP_PCON_START, TYP_PCON_END, TYP_CCM, TYP_KW_FROM, TYP_KW_UPTO, TYP_HP_FROM, TYP_HP_UPTO, TYP_CYLINDERS, ENGINES.ENG_CODE,
					DES_TEXTS2.TEX_TEXT AS TYP_ENGINE_DES_TEXT, DES_TEXTS3.TEX_TEXT AS TYP_FUEL_DES_TEXT,
					IFNULL(DES_TEXTS4.TEX_TEXT, DES_TEXTS5.TEX_TEXT) AS TYP_BODY_DES_TEXT,
					DES_TEXTS6.TEX_TEXT AS TYP_AXLE_DES_TEXT, TYP_MAX_WEIGHT
				FROM TYPES
					INNER JOIN COUNTRY_DESIGNATIONS ON COUNTRY_DESIGNATIONS.CDS_ID = TYP_CDS_ID AND COUNTRY_DESIGNATIONS.CDS_LNG_ID = '.$LNG_ID.'
					INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = COUNTRY_DESIGNATIONS.CDS_TEX_ID
					LEFT JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = TYP_KV_ENGINE_DES_ID AND DESIGNATIONS.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS2 ON DES_TEXTS2.TEX_ID = DESIGNATIONS.DES_TEX_ID
					LEFT JOIN DESIGNATIONS AS DESIGNATIONS2 ON DESIGNATIONS2.DES_ID = TYP_KV_FUEL_DES_ID AND DESIGNATIONS2.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS3 ON DES_TEXTS3.TEX_ID = DESIGNATIONS2.DES_TEX_ID
					LEFT JOIN LINK_TYP_ENG ON LTE_TYP_ID = TYP_ID
					LEFT JOIN ENGINES ON ENG_ID = LTE_ENG_ID
					LEFT JOIN DESIGNATIONS AS DESIGNATIONS3 ON DESIGNATIONS3.DES_ID = TYP_KV_BODY_DES_ID AND DESIGNATIONS3.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS4 ON DES_TEXTS4.TEX_ID = DESIGNATIONS3.DES_TEX_ID
					LEFT JOIN DESIGNATIONS AS DESIGNATIONS4 ON DESIGNATIONS4.DES_ID = TYP_KV_MODEL_DES_ID AND DESIGNATIONS4.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS5 ON DES_TEXTS5.TEX_ID = DESIGNATIONS4.DES_TEX_ID
					LEFT JOIN DESIGNATIONS AS DESIGNATIONS5 ON DESIGNATIONS5.DES_ID = TYP_KV_AXLE_DES_ID AND DESIGNATIONS5.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS6 ON DES_TEXTS6.TEX_ID = DESIGNATIONS5.DES_TEX_ID
				WHERE
					TYP_MOD_ID = '.$MOD_ID.'
				ORDER BY
					TYP_SORT, TYP_CDS_TEXT, TYP_PCON_START, TYP_CCM'; 
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Types auto by id
	static function GetTypeByID($MOD_ID,$TYP_ID,$LNG_ID){
        $SQL='SELECT TYP_ID, DES_TEXTS.TEX_TEXT AS TYP_CDS_TEXT, TYP_PCON_START, TYP_PCON_END, TYP_CCM, TYP_KW_FROM, TYP_KW_UPTO, TYP_HP_FROM, TYP_HP_UPTO, TYP_CYLINDERS, ENGINES.ENG_CODE,
				DES_TEXTS2.TEX_TEXT AS TYP_ENGINE_DES_TEXT, DES_TEXTS3.TEX_TEXT AS TYP_FUEL_DES_TEXT,
				IFNULL(DES_TEXTS4.TEX_TEXT, DES_TEXTS5.TEX_TEXT) AS TYP_BODY_DES_TEXT,
				DES_TEXTS6.TEX_TEXT AS TYP_AXLE_DES_TEXT, TYP_MAX_WEIGHT
			FROM TYPES 
				INNER JOIN COUNTRY_DESIGNATIONS ON COUNTRY_DESIGNATIONS.CDS_ID = TYP_CDS_ID AND COUNTRY_DESIGNATIONS.CDS_LNG_ID = '.$LNG_ID.'
					INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = COUNTRY_DESIGNATIONS.CDS_TEX_ID
					LEFT JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = TYP_KV_ENGINE_DES_ID AND DESIGNATIONS.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS2 ON DES_TEXTS2.TEX_ID = DESIGNATIONS.DES_TEX_ID
					LEFT JOIN DESIGNATIONS AS DESIGNATIONS2 ON DESIGNATIONS2.DES_ID = TYP_KV_FUEL_DES_ID AND DESIGNATIONS2.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS3 ON DES_TEXTS3.TEX_ID = DESIGNATIONS2.DES_TEX_ID
					LEFT JOIN LINK_TYP_ENG ON LTE_TYP_ID = TYP_ID
					LEFT JOIN ENGINES ON ENG_ID = LTE_ENG_ID
					LEFT JOIN DESIGNATIONS AS DESIGNATIONS3 ON DESIGNATIONS3.DES_ID = TYP_KV_BODY_DES_ID AND DESIGNATIONS3.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS4 ON DES_TEXTS4.TEX_ID = DESIGNATIONS3.DES_TEX_ID
					LEFT JOIN DESIGNATIONS AS DESIGNATIONS4 ON DESIGNATIONS4.DES_ID = TYP_KV_MODEL_DES_ID AND DESIGNATIONS4.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS5 ON DES_TEXTS5.TEX_ID = DESIGNATIONS4.DES_TEX_ID
					LEFT JOIN DESIGNATIONS AS DESIGNATIONS5 ON DESIGNATIONS5.DES_ID = TYP_KV_AXLE_DES_ID AND DESIGNATIONS5.DES_LNG_ID = '.$LNG_ID.'
					LEFT JOIN DES_TEXTS AS DES_TEXTS6 ON DES_TEXTS6.TEX_ID = DESIGNATIONS5.DES_TEX_ID
			WHERE TYP_MOD_ID = '.$MOD_ID.' AND TYP_ID='.$TYP_ID; 
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Sections
	static function GetSections($TYP_ID,$PARENT,$LNG_ID){
        $SQL='SELECT
				STR_ID, TEX_TEXT AS STR_DES_TEXT, STR_ID_PARENT, STR_LEVEL, STR_SORT, STR_NODE_NR, 
				IF(EXISTS(SELECT * FROM SEARCH_TREE AS SEARCH_TREE2 WHERE SEARCH_TREE2.STR_ID_PARENT <=> SEARCH_TREE.STR_ID LIMIT 1), 1, 0) AS DESCENDANTS
			FROM SEARCH_TREE
				INNER JOIN DESIGNATIONS ON DES_ID = STR_DES_ID
				INNER JOIN DES_TEXTS ON TEX_ID = DES_TEX_ID
			WHERE
				STR_ID_PARENT <=> '.$PARENT.' AND
				DES_LNG_ID = '.$LNG_ID.' AND
				EXISTS (
					SELECT * FROM LINK_GA_STR
						INNER JOIN LINK_LA_TYP ON LAT_TYP_ID ='.$TYP_ID.' AND LAT_GA_ID = LGS_GA_ID
						INNER JOIN LINK_ART ON LA_ID = LAT_LA_ID
					WHERE
						LGS_STR_ID = STR_ID
					LIMIT 1)
			ORDER BY STR_DES_TEXT'; 
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	static function GetSectionName($SECTION_ID,$LNG_ID){
        if($SECTION_ID<=0 OR $LNG_ID<=0){return false;}
		$SQL='SELECT DES_TEXTS.TEX_TEXT 
			FROM SEARCH_TREE 
				INNER JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = SEARCH_TREE.STR_DES_ID 
				AND DESIGNATIONS.DES_LNG_ID = '.$LNG_ID.' 
				INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = DESIGNATIONS.DES_TEX_ID 
			WHERE
				SEARCH_TREE.STR_ID = '.$SECTION_ID.' ;'; 
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		$arRes = $resDB->GetNext();
		return $arRes;
    }
	//Spare parts
	static function GetParts($TYP_ID,$Section,$LNG_ID,$LIMIT){
        $SQL='SELECT DISTINCT 
				ART_ID, ART_ARTICLE_NR, SUP_BRAND, DES_TEXTS.TEX_TEXT AS STR_DES_TEXT, DES_TEXTS2.TEX_TEXT AS ART_COMPLETE_DES_TEXT  
			FROM LINK_GA_STR
				INNER JOIN LINK_LA_TYP ON LAT_TYP_ID = '.$TYP_ID.' AND 
				LAT_GA_ID = LGS_GA_ID 
				INNER JOIN LINK_ART ON LA_ID = LAT_LA_ID 
				INNER JOIN SEARCH_TREE ON STR_ID = LGS_STR_ID 
				INNER JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = STR_DES_ID AND DESIGNATIONS.DES_LNG_ID = '.$LNG_ID.' 
				INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = DESIGNATIONS.DES_TEX_ID 
				INNER JOIN ARTICLES ON ART_ID = LA_ART_ID 
				INNER JOIN SUPPLIERS ON SUP_ID = ART_SUP_ID 
				INNER JOIN DESIGNATIONS AS DESIGNATIONS2 ON DESIGNATIONS2.DES_ID = ART_COMPLETE_DES_ID 
				INNER JOIN DES_TEXTS AS DES_TEXTS2 ON DES_TEXTS2.TEX_ID = DESIGNATIONS2.DES_TEX_ID AND DESIGNATIONS2.DES_LNG_ID = '.$LNG_ID.' 
			WHERE 
				DES_TEXTS.TEX_TEXT LIKE "%'.$Section.'%" LIMIT '.$LIMIT; //Раздел
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Spare parts (ID section)
	static function GetParts2($TYP_ID,$SECTION_ID,$LIMIT){
        $SQL='SELECT LA_ART_ID, ART_ARTICLE_NR 
			FROM LINK_GA_STR
				INNER JOIN LINK_LA_TYP ON LAT_TYP_ID = '.$TYP_ID.' AND LAT_GA_ID = LGS_GA_ID 
				INNER JOIN LINK_ART ON LA_ID = LAT_LA_ID 
				INNER JOIN ARTICLES ON ART_ID = LA_ART_ID 
			WHERE
				LGS_STR_ID = '.$SECTION_ID.'
			ORDER BY
				LA_ART_ID
			LIMIT '.$LIMIT;
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	static function GetArtByID($ART_ID){
		$SQL="SELECT ART_ARTICLE_NR FROM ARTICLES WHERE ART_ID = ".$ART_ID.";";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB->GetNext();
    }
	static function GetArtIDByNBName($NUMBER,$SUP_BRAND){
		//$SUP_BRAND = str_replace('_plus_',' + ',$SUP_BRAND);
		$SUP_BRAND = str_replace('_and_',' & ',$SUP_BRAND);
		$SUP_BRAND = StrToUp(str_replace('_',' ',$SUP_BRAND));
		$SQL='SELECT ARTICLES.ART_ID
			FROM ART_LOOKUP
				INNER JOIN ARTICLES ON ARTICLES.ART_ID = ART_LOOKUP.ARL_ART_ID
				INNER JOIN SUPPLIERS ON SUPPLIERS.SUP_ID = ARTICLES.ART_SUP_ID
			WHERE
				ART_LOOKUP.ARL_KIND = 1
				AND ART_LOOKUP.ARL_SEARCH_NUMBER = "'.$NUMBER.'"
				AND SUPPLIERS.SUP_BRAND = "'.$SUP_BRAND.'";';
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB->GetNext();
    }
	static function GetArtIDByNBID($NUMBER,$SUP_ID){
		$SQL="SELECT ARTICLES.ART_ID
			FROM ART_LOOKUP
				INNER JOIN ARTICLES ON ARTICLES.ART_ID = ART_LOOKUP.ARL_ART_ID
				INNER JOIN SUPPLIERS ON SUPPLIERS.SUP_ID = ARTICLES.ART_SUP_ID
			WHERE
				ART_LOOKUP.ARL_KIND = 1
				AND ART_LOOKUP.ARL_SEARCH_NUMBER = '".$NUMBER."'
				AND SUPPLIERS.SUP_ID = '".$SUP_ID."';";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB->GetNext();
    }
	//Images
	static function GetImages($ART_ID,$LNG_ID,$LIMIT=0){
        if(intval($LIMIT)>0){$strLIMIT = 'LIMIT '.intval($LIMIT);}
		$SQL="SELECT CONCAT(
					'images/',
					GRA_TAB_NR, '/',
					GRA_GRD_ID, '.',
					IF(LOWER(DOC_EXTENSION)='jp2', 'jpg', LOWER(DOC_EXTENSION))
				) AS PATH 
			FROM	
				LINK_GRA_ART
				INNER JOIN GRAPHICS ON GRA_ID = LGA_GRA_ID
				INNER JOIN DOC_TYPES ON DOC_TYPE = GRA_DOC_TYPE
			WHERE
				LGA_ART_ID = ".$ART_ID." AND
				(GRA_LNG_ID = ".$LNG_ID." OR GRA_LNG_ID = 255) AND
				GRA_DOC_TYPE <> 2
			ORDER BY GRA_GRD_ID ".$strLIMIT.";";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//PDF
	static function GetPDFs($ART_ID,$LNG_ID,$LIMIT=0){
        if(intval($LIMIT)>0){$strLIMIT = 'LIMIT '.intval($LIMIT);}
		$SQL="SELECT CONCAT(
					'pdf/',
					GRA_ID,
					LPAD(GRA_LNG_ID, 3, '0'),
					'.pdf'
				) AS PATH
			FROM
				LINK_GRA_ART
				INNER JOIN GRAPHICS ON GRA_ID = LGA_GRA_ID
			WHERE
				LGA_ART_ID = ".$ART_ID." AND
				(GRA_LNG_ID = ".$LNG_ID." OR GRA_LNG_ID = 255) AND
				GRA_DOC_TYPE = 2
			ORDER BY LGA_ART_ID, GRA_ID, GRA_LNG_ID ".$strLIMIT.";";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Search company by number
	static function LookupByNumber($Number,$LNG_ID){		
		$SQL="SELECT DISTINCT 
				IF (ART_LOOKUP.ARL_KIND IN (3, 4), BRANDS.BRA_BRAND, SUPPLIERS.SUP_BRAND) AS SUP_BRAND,
				ART_LOOKUP.ARL_SEARCH_NUMBER AS ART_ARTICLE_NR,
				ART_LOOKUP.ARL_KIND, 
				DES_TEXTS.TEX_TEXT AS ART_COMPLETE_DES_TEXT
			FROM ART_LOOKUP
				LEFT JOIN BRANDS ON BRANDS.BRA_ID = ART_LOOKUP.ARL_BRA_ID
				INNER JOIN ARTICLES ON ARTICLES.ART_ID = ART_LOOKUP.ARL_ART_ID
				INNER JOIN SUPPLIERS ON SUPPLIERS.SUP_ID = ARTICLES.ART_SUP_ID
				INNER JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = ARTICLES.ART_COMPLETE_DES_ID
				INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = DESIGNATIONS.DES_TEX_ID
			WHERE
				ART_LOOKUP.ARL_SEARCH_NUMBER = '".$Number."' AND
				ART_LOOKUP.ARL_KIND IN (1, 2, 3, 4) AND
				DESIGNATIONS.DES_LNG_ID = ".$LNG_ID."
			GROUP BY SUP_BRAND, ART_ARTICLE_NR;";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Search parts by number and company
	static function LookupByBrandNumber($arNumbers,$arBrands){
		if(defined('SEARCH_LINK_DEEP_CROSSES') AND SEARCH_LINK_DEEP_CROSSES=="Y" AND count($arBrands)>1){
			$DeepCrSQL = "IN ('".implode("','",$arBrands)."')";
		}else{
			$DeepCrSQL = "= '".$arBrands[0]."'"; //First brand must be main brand
		}
		$SQL="SELECT DISTINCT ARTICLES.ART_ID, 
				IF (ART_LOOKUP2.ARL_KIND = 3, BRANDS2.BRA_BRAND, SUPPLIERS2.SUP_BRAND) AS SUP_BRAND,
				IF (ART_LOOKUP2.ARL_KIND IN (2, 3), ART_LOOKUP2.ARL_DISPLAY_NR, ARTICLES2.ART_ARTICLE_NR) AS ART_ARTICLE_NR,
				ART_LOOKUP2.ARL_KIND
			FROM
				ART_LOOKUP
				LEFT JOIN BRANDS ON BRANDS.BRA_ID = ART_LOOKUP.ARL_BRA_ID
				INNER JOIN ARTICLES ON ARTICLES.ART_ID = ART_LOOKUP.ARL_ART_ID
				INNER JOIN SUPPLIERS ON SUPPLIERS.SUP_ID = ARTICLES.ART_SUP_ID
				INNER JOIN ART_LOOKUP AS ART_LOOKUP2 FORCE KEY (PRIMARY) ON ART_LOOKUP2.ARL_ART_ID = ART_LOOKUP.ARL_ART_ID
				LEFT JOIN BRANDS AS BRANDS2 ON BRANDS2.BRA_ID = ART_LOOKUP2.ARL_BRA_ID
				INNER JOIN ARTICLES AS ARTICLES2 ON ARTICLES2.ART_ID = ART_LOOKUP2.ARL_ART_ID
				INNER JOIN SUPPLIERS AS SUPPLIERS2 FORCE KEY (PRIMARY) ON SUPPLIERS2.SUP_ID = ARTICLES2.ART_SUP_ID
			WHERE
				
				ART_LOOKUP.ARL_SEARCH_NUMBER IN ('".implode("','",$arNumbers)."') AND
				(ART_LOOKUP.ARL_KIND IN (3, 4) AND BRANDS.BRA_BRAND ".$DeepCrSQL." OR
				SUPPLIERS.SUP_BRAND IN ('".implode("','",$arBrands)."') ) AND
				
				(ART_LOOKUP.ARL_KIND, ART_LOOKUP2.ARL_KIND) IN
				((1, 1), (1, 2), (1, 3),
				(2, 1), (2, 2), (2, 3),
				(3, 1), (3, 2), (3, 3),
				(4, 1))
			ORDER BY ARL_KIND, SUP_BRAND, ART_ARTICLE_NR;";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	
	//Search for analogues
	static function LookupAnalog($ART_ID,$TYPE){
		$SQL="SELECT ARL_KIND,
				IF (ART_LOOKUP.ARL_KIND = 2, SUPPLIERS.SUP_BRAND, BRANDS.BRA_BRAND) AS BRAND,
				ARL_DISPLAY_NR
			FROM ART_LOOKUP
				 LEFT JOIN BRANDS ON BRA_ID = ARL_BRA_ID
				INNER JOIN ARTICLES ON ARTICLES.ART_ID = ART_LOOKUP.ARL_ART_ID
				INNER JOIN SUPPLIERS ON SUPPLIERS.SUP_ID = ARTICLES.ART_SUP_ID
			WHERE
				ARL_ART_ID = ".$ART_ID." AND ARL_KIND = ".$TYPE." 
			ORDER BY ARL_KIND, BRA_BRAND, ARL_DISPLAY_NR LIMIT 100;";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Search by number
	static function GetIDByNumber($NUMBER,$LNG_ID){
		$SQL="SELECT DISTINCT
				IF (ART_LOOKUP.ARL_KIND IN (3, 4), BRANDS.BRA_BRAND, SUPPLIERS.SUP_BRAND) AS BRAND,
				ART_LOOKUP.ARL_SEARCH_NUMBER AS NUMBER,
				ART_LOOKUP.ARL_ART_ID AS ART_ID
			FROM ART_LOOKUP
				LEFT JOIN BRANDS ON BRANDS.BRA_ID = ART_LOOKUP.ARL_BRA_ID
				INNER JOIN ARTICLES ON ARTICLES.ART_ID = ART_LOOKUP.ARL_ART_ID
				INNER JOIN SUPPLIERS ON SUPPLIERS.SUP_ID = ARTICLES.ART_SUP_ID
				INNER JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = ARTICLES.ART_COMPLETE_DES_ID
				INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = DESIGNATIONS.DES_TEX_ID
			WHERE
				ART_LOOKUP.ARL_SEARCH_NUMBER = '".$NUMBER."' AND 
				ART_LOOKUP.ARL_KIND IN (1, 2, 3, 4) AND 
				DESIGNATIONS.DES_LNG_ID = ".$LNG_ID."
			GROUP BY BRAND, NUMBER;";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	static function GetByNumber($NUMBER,$LNG_ID){
		$SQL="SELECT DISTINCT
				IF (ART_LOOKUP.ARL_KIND IN (3, 4), BRANDS.BRA_BRAND, SUPPLIERS.SUP_BRAND) AS BRAND,
				ART_LOOKUP.ARL_SEARCH_NUMBER AS NUMBER,
				ART_LOOKUP.ARL_KIND,
				ART_LOOKUP.ARL_ART_ID,
				DES_TEXTS.TEX_TEXT AS ART_COMPLETE_DES_TEXT
			FROM ART_LOOKUP
				LEFT JOIN BRANDS ON BRANDS.BRA_ID = ART_LOOKUP.ARL_BRA_ID
				INNER JOIN ARTICLES ON ARTICLES.ART_ID = ART_LOOKUP.ARL_ART_ID
				INNER JOIN SUPPLIERS ON SUPPLIERS.SUP_ID = ARTICLES.ART_SUP_ID
				INNER JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = ARTICLES.ART_COMPLETE_DES_ID
				INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = DESIGNATIONS.DES_TEX_ID
			WHERE
				ART_LOOKUP.ARL_SEARCH_NUMBER = '".$NUMBER."' AND 
				ART_LOOKUP.ARL_KIND IN (1, 2, 3, 4) AND 
				DESIGNATIONS.DES_LNG_ID = ".$LNG_ID."
			GROUP BY BRAND, NUMBER;";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Detailed info. for spare parts
	static function GetPartInfo($ART_ID,$LNG_ID){	
		$SQL="SELECT ART_ID, ART_ARTICLE_NR, SUP_BRAND, SUP_ID, 
				DES_TEXTS.TEX_TEXT AS ART_COMPLETE_DES_TEXT,
				COU_ISO2, DES_TEXTS3.TEX_TEXT AS COU_DES_TEXT
			FROM ARTICLES
				INNER JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = ART_COMPLETE_DES_ID
					AND DESIGNATIONS.DES_LNG_ID = ".$LNG_ID." 
				INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = DESIGNATIONS.DES_TEX_ID
				
				INNER JOIN SUPPLIERS ON SUP_ID = ART_SUP_ID 
				LEFT JOIN SUPPLIER_ADDRESSES ON SAD_SUP_ID = SUP_ID
					AND SAD_COU_ID = 0
				LEFT JOIN COUNTRIES ON COU_ID = SAD_COU_ID_POSTAL
				
				LEFT JOIN DESIGNATIONS AS DESIGNATIONS3 ON DESIGNATIONS3.DES_ID = COU_DES_ID
					AND DESIGNATIONS3.DES_LNG_ID = ".$LNG_ID."
				LEFT JOIN DES_TEXTS AS DES_TEXTS3 ON DES_TEXTS3.TEX_ID = DESIGNATIONS3.DES_TEX_ID
			WHERE ART_ID = ".$ART_ID.";";
			
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB->GetNext();
    }
	//Characteristics
	static function GetPropertys($ART_ID,$LNG_ID){
	   $SQL="SELECT DES_TEXTS.TEX_TEXT AS CRITERIA_DES_TEXT,
				IFNULL(DES_TEXTS2.TEX_TEXT, ACR_VALUE) AS CRITERIA_VALUE_TEXT
			FROM ARTICLE_CRITERIA
				LEFT JOIN DESIGNATIONS AS DESIGNATIONS2 ON DESIGNATIONS2.DES_ID = ACR_KV_DES_ID
				LEFT JOIN DES_TEXTS AS DES_TEXTS2 ON DES_TEXTS2.TEX_ID = DESIGNATIONS2.DES_TEX_ID
				LEFT JOIN CRITERIA ON CRI_ID = ACR_CRI_ID
				LEFT JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = CRI_DES_ID
				LEFT JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = DESIGNATIONS.DES_TEX_ID
			WHERE ACR_ART_ID = ".$ART_ID." AND
				(DESIGNATIONS.DES_LNG_ID IS NULL OR DESIGNATIONS.DES_LNG_ID = ".$LNG_ID.") AND
				(DESIGNATIONS2.DES_LNG_ID IS NULL OR DESIGNATIONS2.DES_LNG_ID = ".$LNG_ID.");";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Detailed info.
	static function GetDopInfo($ART_ID,$LNG_ID){
	   $SQL="SELECT TMT_TEXT AS AIN_TMO_TEXT
			FROM ARTICLE_INFO
				INNER JOIN TEXT_MODULES ON TMO_ID = AIN_TMO_ID
				INNER JOIN TEXT_MODULE_TEXTS ON TMT_ID = TMO_TMT_ID
			WHERE AIN_ART_ID = ".$ART_ID." AND TMO_LNG_ID = ".$LNG_ID."
			ORDER BY AIN_TMO_TEXT;";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	static function GetBrandLogo($ART_ID){
	   $SQL="SELECT CONCAT('images/logos/', SLO_ID, '.png') AS PATH
			FROM ARTICLES
				INNER JOIN SUPPLIER_LOGOS ON SLO_SUP_ID = ART_SUP_ID
			WHERE ART_ID = ".$ART_ID.";";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	
	//Country of the supplier
	static function SupplierCountry($SUP_ID,$LNG_ID){
	   $SQL="SELECT COU_ID, COU_ISO2, TEX_TEXT AS COU_DES_TEXT
			FROM SUPPLIER_ADDRESSES
				INNER JOIN COUNTRIES ON COU_ID = SAD_COU_ID_POSTAL
				INNER JOIN DESIGNATIONS ON DES_ID = COU_DES_ID
				INNER JOIN DES_TEXTS ON TEX_ID = DES_TEX_ID
			WHERE
				SAD_SUP_ID = ".$SUP_ID." AND
				SAD_COU_ID = 0 AND
				DES_LNG_ID = ".$LNG_ID.";";
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
	//Applicability to cars
	static function GetAutoStack($ART_ID,$LNG_ID){
	   $SQL="SELECT TYP_ID, MOD_ID, MFA_BRAND,
				DES_TEXTS7.TEX_TEXT AS MOD_CDS_TEXT,
				DES_TEXTS.TEX_TEXT AS TYP_CDS_TEXT,
				TYP_PCON_START, TYP_PCON_END, TYP_CCM, TYP_KW_FROM, TYP_KW_UPTO, TYP_HP_FROM, TYP_HP_UPTO, TYP_CYLINDERS, ENGINES.ENG_CODE,
				DES_TEXTS2.TEX_TEXT AS TYP_ENGINE_DES_TEXT,
				DES_TEXTS3.TEX_TEXT AS TYP_FUEL_DES_TEXT,
				IFNULL(DES_TEXTS4.TEX_TEXT, DES_TEXTS5.TEX_TEXT) AS TYP_BODY_DES_TEXT,
				DES_TEXTS6.TEX_TEXT AS TYP_AXLE_DES_TEXT,
				TYP_MAX_WEIGHT
			FROM LINK_ART
				INNER JOIN LINK_LA_TYP ON LAT_LA_ID = LA_ID
				INNER JOIN TYPES ON TYP_ID = LAT_TYP_ID
				INNER JOIN COUNTRY_DESIGNATIONS ON COUNTRY_DESIGNATIONS.CDS_ID = TYP_CDS_ID
				INNER JOIN DES_TEXTS ON DES_TEXTS.TEX_ID = COUNTRY_DESIGNATIONS.CDS_TEX_ID
				INNER JOIN MODELS ON MOD_ID = TYP_MOD_ID
				INNER JOIN MANUFACTURERS ON MFA_ID = MOD_MFA_ID
				INNER JOIN COUNTRY_DESIGNATIONS AS COUNTRY_DESIGNATIONS2 ON COUNTRY_DESIGNATIONS2.CDS_ID = MOD_CDS_ID
				INNER JOIN DES_TEXTS AS DES_TEXTS7 ON DES_TEXTS7.TEX_ID = COUNTRY_DESIGNATIONS2.CDS_TEX_ID
				 LEFT JOIN DESIGNATIONS ON DESIGNATIONS.DES_ID = TYP_KV_ENGINE_DES_ID
				 LEFT JOIN DES_TEXTS AS DES_TEXTS2 ON DES_TEXTS2.TEX_ID = DESIGNATIONS.DES_TEX_ID
				 LEFT JOIN DESIGNATIONS AS DESIGNATIONS2 ON DESIGNATIONS2.DES_ID = TYP_KV_FUEL_DES_ID
				 LEFT JOIN DES_TEXTS AS DES_TEXTS3 ON DES_TEXTS3.TEX_ID = DESIGNATIONS2.DES_TEX_ID
				 LEFT JOIN LINK_TYP_ENG ON LTE_TYP_ID = TYP_ID
				 LEFT JOIN ENGINES ON ENG_ID = LTE_ENG_ID
				 LEFT JOIN DESIGNATIONS AS DESIGNATIONS3 ON DESIGNATIONS3.DES_ID = TYP_KV_BODY_DES_ID
				 LEFT JOIN DES_TEXTS AS DES_TEXTS4 ON DES_TEXTS4.TEX_ID = DESIGNATIONS3.DES_TEX_ID
				 LEFT JOIN DESIGNATIONS AS DESIGNATIONS4 ON DESIGNATIONS4.DES_ID = TYP_KV_MODEL_DES_ID
				 LEFT JOIN DES_TEXTS AS DES_TEXTS5 ON DES_TEXTS5.TEX_ID = DESIGNATIONS4.DES_TEX_ID
				 LEFT JOIN DESIGNATIONS AS DESIGNATIONS5 ON DESIGNATIONS5.DES_ID = TYP_KV_AXLE_DES_ID
				 LEFT JOIN DES_TEXTS AS DES_TEXTS6 ON DES_TEXTS6.TEX_ID = DESIGNATIONS5.DES_TEX_ID
			WHERE
				LA_ART_ID = ".$ART_ID." AND
				COUNTRY_DESIGNATIONS.CDS_LNG_ID = ".$LNG_ID." AND
				COUNTRY_DESIGNATIONS2.CDS_LNG_ID = ".$LNG_ID." AND
				(DESIGNATIONS.DES_LNG_ID IS NULL OR DESIGNATIONS.DES_LNG_ID = ".$LNG_ID.") AND
				(DESIGNATIONS2.DES_LNG_ID IS NULL OR DESIGNATIONS2.DES_LNG_ID = ".$LNG_ID.") AND
				(DESIGNATIONS3.DES_LNG_ID IS NULL OR DESIGNATIONS3.DES_LNG_ID = ".$LNG_ID.") AND
				(DESIGNATIONS4.DES_LNG_ID IS NULL OR DESIGNATIONS4.DES_LNG_ID = ".$LNG_ID.") AND
				(DESIGNATIONS5.DES_LNG_ID IS NULL OR DESIGNATIONS5.DES_LNG_ID = ".$LNG_ID.")
			ORDER BY MFA_BRAND, MOD_CDS_TEXT, TYP_CDS_TEXT, TYP_PCON_START, TYP_CCM
			LIMIT 1000;"; 
		$resDB = new TDSQLQuery;
		$resDB->QuerySelect($SQL);
		return $resDB;
    }
}

class TDSQLQuery{
	var $Error;
	var $Result;
    var $NumRows; 
	
	function GetNext(){
        if($this->NumRows>0){
            $arResult = mysql_fetch_assoc($this->Result);
            return $arResult;
        }else{$this->Error="No records"; return false;}
    }
	function QuerySelect($SQL){
		$resQuery = mysql_query($SQL);
		if($resQuery){
			$this->NumRows = mysql_num_rows($resQuery);
			if($this->NumRows>0){$this->Result = $resQuery;}else{$this->Error="No records"; return false;}
		}else{$this->Error="No records"; return false;}
	}
}
?>